{{- if .Values.terminatingGateways.enabled }}

{{- $root := . }}
{{- $defaults := .Values.terminatingGateways.defaults }}

{{- range .Values.terminatingGateways.gateways }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app: {{ template "consul.name" $root }}
    chart: {{ template "consul.chart" $root }}
    heritage: {{ $root.Release.Service }}
    release: {{ $root.Release.Name }}
    component: terminating-gateway
{{- if (or $root.Values.global.acls.manageSystemACLs $root.Values.global.bootstrapACLs $root.Values.global.enablePodSecurityPolicies) }}
rules:
{{- if $root.Values.global.enablePodSecurityPolicies }}
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames:
      - {{ .name }}
    verbs:
      - use
{{- end }}
{{- if (or $root.Values.global.acls.manageSystemACLs $root.Values.global.bootstrapACLs) }}
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - {{ .name }}-terminating-gateway-acl-token
    verbs:
      - get
{{- end }}
{{- else }}
rules: []
{{- end }}
---
{{- end }}
{{- end }}
